name: Build Totem QMK configuration

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  build-qmk:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: d3adb5/build-qmk-fw@v1
        with:
          keyboard: totem/qwerty
          keymap: qwerty
          local-keymap-path: totem/keymaps/qwerty
          output-dir: totem-qwerty

      - uses: actions/upload-artifact@v4
        with:
          name: built-images
          path: totem-qwerty